---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gajala
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gajala
  template:
    metadata:
      labels:
        app: gajala
    spec:
      containers:
      - name: gajala
        image: satishflm/kubernetesproject:FoodDeliveryApp
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gajala-service
spec:
  selector:
    app: gajala
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
